/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/C5h4G1PGx5i
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { IBM_Plex_Sans } from 'next/font/google'
import { Gabarito } from 'next/font/google'

ibm_plex_sans({
  subsets: ['latin'],
  display: 'swap',
})

gabarito({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { JSX, SVGProps } from "react"

export function About() {
  return (
    <div className="flex flex-col min-h-[100dvh]">
      <main className="flex-1">
        <section className="w-full py-12 md:py-24 lg:py-32">
          <div className="container px-4 md:px-6 grid gap-8 lg:grid-cols-2 lg:gap-16">
            <div className="space-y-4">
              <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">About Acme Inc</h1>
              <p className="text-muted-foreground md:text-xl">
                Acme Inc is a leading e-commerce company dedicated to providing high-quality products and exceptional
                customer service. Our mission is to make online shopping a seamless and enjoyable experience for our
                customers.
              </p>
            </div>
            <img
              src="/placeholder.svg"
              width="550"
              height="550"
              alt="About"
              className="mx-auto aspect-square overflow-hidden rounded-xl object-cover sm:w-full"
            />
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 bg-muted">
          <div className="container px-4 md:px-6 grid gap-8 lg:grid-cols-2 lg:gap-16">
            <div className="space-y-4">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Our Values</h2>
              <p className="text-muted-foreground md:text-xl">
                At Acme Inc, we are guided by a set of core values that underpin everything we do. These include a
                commitment to quality, innovation, sustainability, and exceptional customer service.
              </p>
            </div>
            <div className="space-y-4">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Our History</h2>
              <p className="text-muted-foreground md:text-xl">
                Acme Inc was founded in 2010 with the goal of revolutionizing the e-commerce industry. Over the past
                decade, we have grown to become one of the most trusted and respected brands in the online retail space,
                thanks to our unwavering dedication to our customers and our commitment to continuous improvement.
              </p>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32">
          <div className="container px-4 md:px-6 grid gap-8 lg:grid-cols-2 lg:gap-16">
            <div className="space-y-4">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Our Team</h2>
              <p className="text-muted-foreground md:text-xl">
                At the heart of Acme Inc are our talented and dedicated team members. From our founders to our customer
                service representatives, each and every one of us is passionate about delivering the best possible
                experience to our customers.
              </p>
            </div>
            <div className="grid grid-cols-2 gap-6">
              <div className="flex flex-col items-center space-y-2">
                <Avatar>
                  <AvatarImage src="/placeholder-user.jpg" />
                  <AvatarFallback>JD</AvatarFallback>
                </Avatar>
                <div className="text-center">
                  <p className="text-sm font-medium">John Doe</p>
                  <p className="text-sm text-muted-foreground">CEO</p>
                </div>
              </div>
              <div className="flex flex-col items-center space-y-2">
                <Avatar>
                  <AvatarImage src="/placeholder-user.jpg" />
                  <AvatarFallback>JL</AvatarFallback>
                </Avatar>
                <div className="text-center">
                  <p className="text-sm font-medium">Jane Loe</p>
                  <p className="text-sm text-muted-foreground">CTO</p>
                </div>
              </div>
              <div className="flex flex-col items-center space-y-2">
                <Avatar>
                  <AvatarImage src="/placeholder-user.jpg" />
                  <AvatarFallback>SM</AvatarFallback>
                </Avatar>
                <div className="text-center">
                  <p className="text-sm font-medium">Sarah Miller</p>
                  <p className="text-sm text-muted-foreground">CMO</p>
                </div>
              </div>
              <div className="flex flex-col items-center space-y-2">
                <Avatar>
                  <AvatarImage src="/placeholder-user.jpg" />
                  <AvatarFallback>JB</AvatarFallback>
                </Avatar>
                <div className="text-center">
                  <p className="text-sm font-medium">John Boe</p>
                  <p className="text-sm text-muted-foreground">COO</p>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}

function MountainIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  )
}
