/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/MjUU45ZCouc
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Arimo } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

arimo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { Carousel, CarouselContent, CarouselItem, CarouselPrevious, CarouselNext } from "@/components/ui/carousel"
import { Card, CardContent } from "@/components/ui/card"
import { JSX, SVGProps } from "react"
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuSeparator, DropdownMenuTrigger } from "../ui/dropdown-menu"
import { Avatar, AvatarFallback, AvatarImage } from "../ui/avatar"
import LogoutBtn from "../functional/LogoutBtn"
import {dummyProducts} from '@/dummy/products'
import ToggleMenuBtn from "../functional/ToggleMenuBtn"
import { UserRound } from "lucide-react"
import ProductCard from "../functional/ProductCard"

export function Homepage({user}:{user:any}) {
  return (
    <div className="flex flex-col min-h-screen overflow-x-hidden ">
      
      
      <main className="flex-1">
        <Carousel className="w-full max-w-6xl mx-auto">
          <CarouselContent>
            <CarouselItem>
              <div className="relative h-[400px] bg-[url('/placeholder.svg')] bg-cover bg-center flex items-center justify-center">
                <div className="bg-primary/80 text-primary-foreground p-8 rounded-md text-center max-w-md">
                  <h1 className="text-3xl font-bold mb-4">Discover the Latest Trends</h1>
                  <p className="mb-6">Explore our curated collection of fashionable and high-quality products.</p>
                  <Link
                    href="#"
                    className="inline-flex items-center justify-center rounded-md bg-primary-foreground px-4 py-2 text-primary font-medium hover:bg-primary/90 focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2"
                    prefetch={false}
                  >
                    Shop Now
                  </Link>
                </div>
              </div>
            </CarouselItem>
            <CarouselItem>
              <div className="relative h-[400px] bg-[url('/placeholder.svg')] bg-cover bg-center flex items-center justify-center">
                <div className="bg-primary/80 text-primary-foreground p-8 rounded-md text-center max-w-md">
                  <h1 className="text-3xl font-bold mb-4">Discover the Latest Trends</h1>
                  <p className="mb-6">Explore our curated collection of fashionable and high-quality products.</p>
                  <Link
                    href="#"
                    className="inline-flex items-center justify-center rounded-md bg-primary-foreground px-4 py-2 text-primary font-medium hover:bg-primary/90 focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2"
                    prefetch={false}
                  >
                    Shop Now
                  </Link>
                </div>
              </div>
            </CarouselItem>
            <CarouselItem>
              <div className="relative h-[400px] bg-[url('/placeholder.svg')] bg-cover bg-center flex items-center justify-center">
                <div className="bg-primary/80 text-primary-foreground p-8 rounded-md text-center max-w-md">
                  <h1 className="text-3xl font-bold mb-4">Discover the Latest Trends</h1>
                  <p className="mb-6">Explore our curated collection of fashionable and high-quality products.</p>
                  <Link
                    href="#"
                    className="inline-flex items-center justify-center rounded-md bg-primary-foreground px-4 py-2 text-primary font-medium hover:bg-primary/90 focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2"
                    prefetch={false}
                  >
                    Shop Now
                  </Link>
                </div>
              </div>
            </CarouselItem>
          </CarouselContent>
          <CarouselPrevious className=" absolute left-0"/>
          <CarouselNext  className="absolute right-0"/>
        </Carousel>
        <section className="py-12 px-6 md:px-12">
          <div className="max-w-5xl mx-auto">
            <h2 className="text-2xl font-bold mb-6">Featured Products</h2>
            <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
              {dummyProducts.slice(0,10).map((product,ind)=>{
                return(
                  <ProductCard product={product}/>
                )
              })}
              
            </div>
          </div>
        </section>
        <section className="bg-muted py-12 px-6 md:px-12">
          <div className="max-w-5xl mx-auto">
            <h2 className="text-2xl font-bold mb-6">New Arrivals</h2>
            <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
              <Card>
                <img
                  src="/placeholder.svg"
                  width={300}
                  height={300}
                  alt="Product Image"
                  className="rounded-t-md object-cover w-full aspect-square"
                />
                <CardContent className="p-4">
                  <h3 className="text-lg font-semibold mb-2">Product Name</h3>
                  <p className="text-muted-foreground mb-4">Product Description</p>
                  <div className="flex items-center justify-between">
                    <span className="font-bold text-lg">$59.99</span>
                    <Button>Add to Cart</Button>
                  </div>
                </CardContent>
              </Card>
              <Card>
                <img
                  src="/placeholder.svg"
                  width={300}
                  height={300}
                  alt="Product Image"
                  className="rounded-t-md object-cover w-full aspect-square"
                />
                <CardContent className="p-4">
                  <h3 className="text-lg font-semibold mb-2">Product Name</h3>
                  <p className="text-muted-foreground mb-4">Product Description</p>
                  <div className="flex items-center justify-between">
                    <span className="font-bold text-lg">$69.99</span>
                    <Button>Add to Cart</Button>
                  </div>
                </CardContent>
              </Card>
              <Card>
                <img
                  src="/placeholder.svg"
                  width={300}
                  height={300}
                  alt="Product Image"
                  className="rounded-t-md object-cover w-full aspect-square"
                />
                <CardContent className="p-4">
                  <h3 className="text-lg font-semibold mb-2">Product Name</h3>
                  <p className="text-muted-foreground mb-4">Product Description</p>
                  <div className="flex items-center justify-between">
                    <span className="font-bold text-lg">$79.99</span>
                    <Button>Add to Cart</Button>
                  </div>
                </CardContent>
              </Card>
              <Card>
                <img
                  src="/placeholder.svg"
                  width={300}
                  height={300}
                  alt="Product Image"
                  className="rounded-t-md object-cover w-full aspect-square"
                />
                <CardContent className="p-4">
                  <h3 className="text-lg font-semibold mb-2">Product Name</h3>
                  <p className="text-muted-foreground mb-4">Product Description</p>
                  <div className="flex items-center justify-between">
                    <span className="font-bold text-lg">$89.99</span>
                    <Button>Add to Cart</Button>
                  </div>
                </CardContent>
              </Card>
            </div>
          </div>
        </section>
        <section className="py-12 px-6 md:px-12">
          <div className="max-w-5xl mx-auto">
            <h2 className="text-2xl font-bold mb-6">Popular Categories</h2>
            <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-6 gap-6">
              <Link
                href="#"
                className="bg-muted rounded-md p-4 flex flex-col items-center justify-center hover:bg-accent hover:text-accent-foreground transition-colors"
                prefetch={false}
              >
                <ShirtIcon className="h-8 w-8 mb-2" />
                <span className="text-sm font-medium">Clothing</span>
              </Link>
              <Link
                href="#"
                className="bg-muted rounded-md p-4 flex flex-col items-center justify-center hover:bg-accent hover:text-accent-foreground transition-colors"
                prefetch={false}
              >
                <FootprintsIcon className="h-8 w-8 mb-2" />
                <span className="text-sm font-medium">Shoes</span>
              </Link>
              <Link
                href="#"
                className="bg-muted rounded-md p-4 flex flex-col items-center justify-center hover:bg-accent hover:text-accent-foreground transition-colors"
                prefetch={false}
              >
                <ShoppingBagIcon className="h-8 w-8 mb-2" />
                <span className="text-sm font-medium">Bags</span>
              </Link>
              <Link
                href="#"
                className="bg-muted rounded-md p-4 flex flex-col items-center justify-center hover:bg-accent hover:text-accent-foreground transition-colors"
                prefetch={false}
              >
                <WatchIcon className="h-8 w-8 mb-2" />
                <span className="text-sm font-medium">Accessories</span>
              </Link>
              <Link
                href="#"
                className="bg-muted rounded-md p-4 flex flex-col items-center justify-center hover:bg-accent hover:text-accent-foreground transition-colors"
                prefetch={false}
              >
                <LaptopIcon className="h-8 w-8 mb-2" />
                <span className="text-sm font-medium">Electronics</span>
              </Link>
              <Link
                href="#"
                className="bg-muted rounded-md p-4 flex flex-col items-center justify-center hover:bg-accent hover:text-accent-foreground transition-colors"
                prefetch={false}
              >
                <HomeIcon className="h-8 w-8 mb-2" />
                <span className="text-sm font-medium">Home</span>
              </Link>
            </div>
          </div>
        </section>
      </main>
      <footer className="bg-primary text-primary-foreground py-6 px-6">
        <div className="max-w-5xl mx-auto flex flex-col md:flex-row items-center justify-between">
          <p className="text-sm">&copy; 2024 Acme Store. All rights reserved.</p>
          <nav className="flex items-center gap-4 mt-4 md:mt-0">
            <Link href="#" className="hover:underline" prefetch={false}>
              Terms of Service
            </Link>
            <Link href="#" className="hover:underline" prefetch={false}>
              Privacy Policy
            </Link>
            <Link href="#" className="hover:underline" prefetch={false}>
              Contact Us
            </Link>
          </nav>
        </div>
      </footer>
    </div>
  )
}

function FootprintsIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 16v-2.38C4 11.5 2.97 10.5 3 8c.03-2.72 1.49-6 4.5-6C9.37 2 10 3.8 10 5.5c0 3.11-2 5.66-2 8.68V16a2 2 0 1 1-4 0Z" />
      <path d="M20 20v-2.38c0-2.12 1.03-3.12 1-5.62-.03-2.72-1.49-6-4.5-6C14.63 6 14 7.8 14 9.5c0 3.11 2 5.66 2 8.68V20a2 2 0 1 0 4 0Z" />
      <path d="M16 17h4" />
      <path d="M4 13h4" />
    </svg>
  )
}


function HomeIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m3 9 9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z" />
      <polyline points="9 22 9 12 15 12 15 22" />
    </svg>
  )
}


function LaptopIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20 16V7a2 2 0 0 0-2-2H6a2 2 0 0 0-2 2v9m16 0H4m16 0 1.28 2.55a1 1 0 0 1-.9 1.45H3.62a1 1 0 0 1-.9-1.45L4 16" />
    </svg>
  )
}


function MenuIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>
  )
}


function MountainIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  )
}


function SearchIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  )
}


function ShirtIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20.38 3.46 16 2a4 4 0 0 1-8 0L3.62 3.46a2 2 0 0 0-1.34 2.23l.58 3.47a1 1 0 0 0 .99.84H6v10c0 1.1.9 2 2 2h8a2 2 0 0 0 2-2V10h2.15a1 1 0 0 0 .99-.84l.58-3.47a2 2 0 0 0-1.34-2.23z" />
    </svg>
  )
}


function ShoppingBagIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M6 2 3 6v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V6l-3-4Z" />
      <path d="M3 6h18" />
      <path d="M16 10a4 4 0 0 1-8 0" />
    </svg>
  )
}


function ShoppingCartIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="8" cy="21" r="1" />
      <circle cx="19" cy="21" r="1" />
      <path d="M2.05 2.05h2l2.66 12.42a2 2 0 0 0 2 1.58h9.78a2 2 0 0 0 1.95-1.57l1.65-7.43H5.12" />
    </svg>
  )
}


function WatchIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="6" />
      <polyline points="12 10 12 12 13 13" />
      <path d="m16.13 7.66-.81-4.05a2 2 0 0 0-2-1.61h-2.68a2 2 0 0 0-2 1.61l-.78 4.05" />
      <path d="m7.88 16.36.8 4a2 2 0 0 0 2 1.61h2.72a2 2 0 0 0 2-1.61l.81-4.05" />
    </svg>
  )
}


function XIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}
