/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/0blp0BDEmzZ
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Archivo } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

archivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import { Separator } from "@/components/ui/separator"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { JSX, SVGProps } from "react"

export function Productview() {
  return (
    <div className="grid md:grid-cols-2 gap-6 lg:gap-12 items-start max-w-6xl px-4 mx-auto py-6">
      <div className="grid gap-4">
        <img
          src="/placeholder.svg"
          alt="Product Image"
          width={600}
          height={900}
          className="aspect-[2/3] object-cover border w-full rounded-lg overflow-hidden"
        />
        <div className="hidden md:flex gap-4 items-start">
          <button className="border hover:border-primary rounded-lg overflow-hidden transition-colors">
            <img
              src="/placeholder.svg"
              alt="Preview thumbnail"
              width={100}
              height={100}
              className="aspect-square object-cover"
            />
            <span className="sr-only">View Image 1</span>
          </button>
          <button className="border hover:border-primary rounded-lg overflow-hidden transition-colors">
            <img
              src="/placeholder.svg"
              alt="Preview thumbnail"
              width={100}
              height={100}
              className="aspect-square object-cover"
            />
            <span className="sr-only">View Image 2</span>
          </button>
          <button className="border hover:border-primary rounded-lg overflow-hidden transition-colors">
            <img
              src="/placeholder.svg"
              alt="Preview thumbnail"
              width={100}
              height={100}
              className="aspect-square object-cover"
            />
            <span className="sr-only">View Image 3</span>
          </button>
          <button className="border hover:border-primary rounded-lg overflow-hidden transition-colors">
            <img
              src="/placeholder.svg"
              alt="Preview thumbnail"
              width={100}
              height={100}
              className="aspect-square object-cover"
            />
            <span className="sr-only">View Image 4</span>
          </button>
        </div>
      </div>
      <div className="grid gap-4 md:gap-10 items-start">
        <div className="grid gap-4">
          <h1 className="font-bold text-3xl lg:text-4xl">Acme Prism T-Shirt: The Cozy Chromatic Blend</h1>
          <div className="flex items-center gap-4">
            <div className="flex items-center gap-0.5">
              <StarIcon className="w-5 h-5 fill-primary" />
              <StarIcon className="w-5 h-5 fill-primary" />
              <StarIcon className="w-5 h-5 fill-primary" />
              <StarIcon className="w-5 h-5 fill-muted stroke-muted-foreground" />
              <StarIcon className="w-5 h-5 fill-muted stroke-muted-foreground" />
            </div>
            <p className="text-sm text-muted-foreground">(12 reviews)</p>
          </div>
          <div>
            <p>
              Introducing the Acme Prism T-Shirt, a perfect blend of style and comfort for the modern individual. This
              tee is crafted with a meticulous composition of 60% combed ringspun cotton and 40% polyester jersey,
              ensuring a soft and breathable fabric that feels gentle against the skin.
            </p>
            <p className="mt-4">
              The design of the Acme Prism T-Shirt is as striking as it is comfortable. The shirt features a unique
              prism-inspired pattern that adds a modern and eye-catching touch to your ensemble.
            </p>
          </div>
        </div>
        <div className="grid gap-4">
          <div className="flex items-center justify-between">
            <h2 className="font-bold text-2xl">$49.99</h2>
            <Button size="lg">Add to Cart</Button>
          </div>
          <Separator />
          <div className="grid gap-4">
            <h2 className="font-bold text-xl">Product Specifications</h2>
            <div className="grid sm:grid-cols-2 gap-4">
              <div className="grid gap-1">
                <p className="font-medium">Material</p>
                <p>60% combed ringspun cotton, 40% polyester</p>
              </div>
              <div className="grid gap-1">
                <p className="font-medium">Fit</p>
                <p>Regular</p>
              </div>
              <div className="grid gap-1">
                <p className="font-medium">Sleeve Length</p>
                <p>Short</p>
              </div>
              <div className="grid gap-1">
                <p className="font-medium">Neck</p>
                <p>Crew</p>
              </div>
            </div>
          </div>
          <Separator />
          <div className="grid gap-4">
            <h2 className="font-bold text-xl">Customer Reviews</h2>
            <div className="grid gap-6">
              <div className="flex gap-4">
                <Avatar className="w-10 h-10 border">
                  <AvatarImage src="/placeholder-user.jpg" />
                  <AvatarFallback>CN</AvatarFallback>
                </Avatar>
                <div className="grid gap-4">
                  <div className="flex gap-4 items-start">
                    <div className="grid gap-0.5 text-sm">
                      <h3 className="font-semibold">Sarah Johnson</h3>
                      <time className="text-sm text-muted-foreground">2 days ago</time>
                    </div>
                    <div className="flex items-center gap-0.5 ml-auto">
                      <StarIcon className="w-5 h-5 fill-primary" />
                      <StarIcon className="w-5 h-5 fill-primary" />
                      <StarIcon className="w-5 h-5 fill-primary" />
                      <StarIcon className="w-5 h-5 fill-muted stroke-muted-foreground" />
                      <StarIcon className="w-5 h-5 fill-muted stroke-muted-foreground" />
                    </div>
                  </div>
                  <div className="text-sm leading-loose text-muted-foreground">
                    <p>
                      I&apos;ve been experimenting with my Acme Prism T-Shirt for a few weeks now, and it&apos;s been a
                      versatile addition to my wardrobe. The unique pattern and comfortable fit make it a go-to for both
                      casual and slightly dressier occasions.
                    </p>
                  </div>
                </div>
              </div>
              <div className="flex gap-4">
                <Avatar className="w-10 h-10 border">
                  <AvatarImage src="/placeholder-user.jpg" />
                  <AvatarFallback>CN</AvatarFallback>
                </Avatar>
                <div className="grid gap-4">
                  <div className="flex gap-4 items-start">
                    <div className="grid gap-0.5 text-sm">
                      <h3 className="font-semibold">Alex Smith</h3>
                      <time className="text-sm text-muted-foreground">3 weeks ago</time>
                    </div>
                    <div className="flex items-center gap-0.5 ml-auto">
                      <StarIcon className="w-5 h-5 fill-primary" />
                      <StarIcon className="w-5 h-5 fill-primary" />
                      <StarIcon className="w-5 h-5 fill-primary" />
                      <StarIcon className="w-5 h-5 fill-muted stroke-muted-foreground" />
                      <StarIcon className="w-5 h-5 fill-muted stroke-muted-foreground" />
                    </div>
                  </div>
                  <div className="text-sm leading-loose text-muted-foreground">
                    <p>
                      The Acme Prism T-Shirt is a great addition to my wardrobe. The fabric is soft and breathable, and
                      the unique pattern adds a touch of style to my casual outfits. I&apos;ve received several
                      compliments on it already.
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <Separator />
          <div className="grid gap-4">
            <h2 className="font-bold text-xl">Related Products</h2>
            <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-6">
              <div className="grid gap-4">
                <img
                  src="/placeholder.svg"
                  alt="Related Product 1"
                  width={300}
                  height={300}
                  className="aspect-square object-cover border rounded-lg"
                />
                <div className="grid gap-1">
                  <h3 className="font-semibold">Acme Circles T-Shirt</h3>
                  <p className="text-sm text-muted-foreground">60% combed ringspun cotton/40% polyester jersey tee.</p>
                  <p className="font-semibold">$39.99</p>
                </div>
              </div>
              <div className="grid gap-4">
                <img
                  src="/placeholder.svg"
                  alt="Related Product 2"
                  width={300}
                  height={300}
                  className="aspect-square object-cover border rounded-lg"
                />
                <div className="grid gap-1">
                  <h3 className="font-semibold">Acme Stripes Hoodie</h3>
                  <p className="text-sm text-muted-foreground">80% cotton, 20% polyester fleece.</p>
                  <p className="font-semibold">$59.99</p>
                </div>
              </div>
              <div className="grid gap-4">
                <img
                  src="/placeholder.svg"
                  alt="Related Product 3"
                  width={300}
                  height={300}
                  className="aspect-square object-cover border rounded-lg"
                />
                <div className="grid gap-1">
                  <h3 className="font-semibold">Acme Joggers</h3>
                  <p className="text-sm text-muted-foreground">90% cotton, 10% spandex.</p>
                  <p className="font-semibold">$49.99</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

function StarIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" />
    </svg>
  )
}


function XIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}
