/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/4QInxT14jDW
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Archivo } from 'next/font/google'
import { Libre_Franklin } from 'next/font/google'

archivo({
  subsets: ['latin'],
  display: 'swap',
})

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
// "use client"

import { JSX, SVGProps } from "react"
import { getProductsByCategoryAndQuery } from "@/actions/product"
import {  productDataGetting } from "@/types/product"
import ProductCard from "../functional/ProductCard"
import FunctionalPagination from "../functional/FunctionalPagination"

export async function SearchPage({category,query,page}:{category:string,query:string,page:number}) {
  console.log(42,category,query,page)
  const products = [
    {
      id: 1,
      image: "/placeholder.svg",
      title: "Wireless Headphones",
      price: 79.99,
      rating: 4.5,
      category: "Electronics",
    },
    {
      id: 2,
      image: "/placeholder.svg",
      title: "Leather Backpack",
      price: 59.99,
      rating: 4.2,
      category: "Bags",
    },
    {
      id: 3,
      image: "/placeholder.svg",
      title: "Outdoor Camping Gear",
      price: 99.99,
      rating: 4.8,
      category: "Outdoors",
    },
    {
      id: 4,
      image: "/placeholder.svg",
      title: "Stylish Sunglasses",
      price: 29.99,
      rating: 4.3,
      category: "Accessories",
    },
    {
      id: 5,
      image: "/placeholder.svg",
      title: "Ergonomic Office Chair",
      price: 149.99,
      rating: 4.6,
      category: "Furniture",
    },
    {
      id: 6,
      image: "/placeholder.svg",
      title: "Smart Home Hub",
      price: 89.99,
      rating: 4.4,
      category: "Electronics",
    },
    {
      id: 7,
      image: "/placeholder.svg",
      title: "Fitness Tracker Watch",
      price: 69.99,
      rating: 4.7,
      category: "Wearables",
    },
    {
      id: 8,
      image: "/placeholder.svg",
      title: "Luxury Throw Blanket",
      price: 79.99,
      rating: 4.9,
      category: "Home",
    },
  ]

  const queryProducts:productDataGetting=await getProductsByCategoryAndQuery({limit:6,page:page,query:query,category})


  return (
    <>
      

        <section className="bg-muted py-12 px-6 md:px-12">
            <div className="max-w-[1500px] mx-auto">
                <h2 className="text-2xl font-bold mb-6">Category: {category}</h2>
                <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
                {
                    queryProducts?.products?.map((product,ind)=>{
                    return(
                        <ProductCard key={product._id} product={product}/>
                    )
                    })
                }
                </div>
                <FunctionalPagination currentPage={queryProducts.currentPage} totalPages={queryProducts.totalPages} />
            </div>
        </section>


    </>
  )
}

function StarIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" />
    </svg>
  )
}


function XIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}
